# Rotor's postion 
ROTOR_P_X: 0.11
ROTOR_P_Y: 0.11

# Dataset segment 
DATASET_S: 2000
# DATASET_L: 3000
DATASET_L: 12000

# Thrust sigma of z-axis direction
P_T_SIGMA: 0.1

# Unmodel thrust sigma of xy-axis direction 
U_T_SIGMA: 0.05

ENABLE_DRAG: TRUE

# INERTIA_IX: 0.049
# INERTIA_IY: 0.049
# INERTIA_IZ: 0.069


INERTIA_IX: 0.00351
INERTIA_IY: 0.00366
INERTIA_IZ: 0.005


ENABLE_I:    FALSE

ENABLE_COG: TRUE

ENABLE_VISCOUS: TRUE


# Data file path
# ROOT_PATH: ../data/blackbird/ampersand/yawConstant/maxSpeed3p0
ROOT_PATH: ../data/blackbird/pacasso/yawForward/maxSpeed4p0
# ROOT_PATH: ../data/blackbird/ampersand/yawForward/maxSpeed2p0
