# PRI_VICON_COV: 0.05

# PRIOR_U_F_COV: 10.0
# PRIOR_U_M1_COV: 0.1
# PRIOR_U_M2_COV: 0.1
# PRIOR_U_M3_COV: 0.1

# CONTROL_P_COV: 0.03
# CONTROL_P_FINAL_COV: 0.005
# CONTROL_R_COV: 0.01

# DYNAMIC_P_COV: 0.001

# OPT_LENS_TRAJ: 20

# SIM_STEPS: 30000

PRI_VICON_COV: 0.05

PRIOR_U_F_COV: 10.0
PRIOR_U_M1_COV: 0.1
PRIOR_U_M2_COV: 0.1
PRIOR_U_M3_COV: 0.1

CONTROL_P_COV: 0.03
CONTROL_P_FINAL_COV: 0.005
CONTROL_R_COV: 0.01

DYNAMIC_P_COV: 0.001

OPT_LENS_TRAJ: 20

SIM_STEPS: 30000
