AT_NOISE_MEAN: 0.0
AT_NOISE_COV: 0.3
ANGULAR_SPEED_MEAN: 0.0
ANGULAR_SPEED_COV: 0.005

RADIUS: 1.0
LINEAR_VEL: 3.0

# POSITION MEASUREMENT COVARIANCE FROM VICON
POS_MEAS_MEAN: 0.00
POS_MEAS_COV: 0.05

# Drag force 
DRAG_FORCE_X: 0.0
DRAG_FORCE_Y: 0.0
DRAG_FORCE_Z: 0.0

# Environment Simulation
MAP_X: 5.0
MAP_Y: 5.0
MAP_Z: 2.0

MAP_CENTER_X: 0.0
MAP_CENTER_Y: 0.0
MAP_CENTER_Z: 1.0

LANDMARKS_SIZE: 1000
LIDAR_RANGE: 0.60
LIDAR_RANGE_MIN: 0.10